### PR TITLE
Remove underscore.js library _.max and _.times function

### PR DESCRIPTION
**Pull request by m-sureshraj**
- Remove _.max and _.times function.
-  Add helper object with times() and getMaxRaw() methods. ( these method's provide similar functionality like max and time ).
- Replace the _.max and _.times function usage with helper methods.

### CODE REVIEW

**Comment by ncthis** [comment]
Thanks! Looks great.

Can you please...

1. Remove the spaces in parens 
2. Generate the minified version as well
3. And update the demo directory

Sorry about that. Haven't gotten around to put in a linter and a build script for this yet.

**Comment by m-sureshraj** [comment]
Thanks for the replay..

Sorry for the spaces issue, i usually follow jquery style guide to write js. I plan to add grunt to the project for build task. thanks.

**Comment by m-sureshraj** [comment]
Changes are done.

1. Remove the spaces in parens
2. generate minified version

new changes
1. Adding grunt task runner to the project

can u please update the package.json file info.

**Comment by nadeesha** [comment]
I'm deprecating the library because the problem it tries to solve is better solved by [Gridstack](http://troolee.github.io/gridstack.js/). If you want to maintain a fork, feel free. Thanks!

**Pull request closed without merging**
